### ISSUE TITLE
Why UserBuy.csv file is required when I test the 'taobao' dataset?

### ISSUE THREAD

**Issue by xiqxin1** [tsinghua-fib-lab/SIGIR21-SURGE#10]
Hi,

Thank you very much for the excellent code. I'm now testing the 'taobao' dataset. I download the UserBehavior.csv file from the link you mentioned in the paper, but there is no UserBuy.csv file, which is required in your code (at sequential_reviews.py, line 46, in the strong_data_preprocessing function). Could you tell me more about how to implement your code?
https://tianchi.aliyun.com/dataset/dataDetail?dataId=649

Thanks a lot.

**Comment by unknowed-ER** [comment]
Have you solved the third problem？

**Comment by unknowed-ER** [comment]
./data/data.md maybe helps you find that file

**Comment by xiqxin1** [comment]
Thanks a lot!
