### ISSUE TITLE
Question about datesets

### ISSUE THREAD

**Issue by liuhui0401** [tsinghua-fib-lab/SIGIR21-SURGE#2]
The dataset file for kuaishou is empty. The dataset file for taobao is too large to download. Could you please solve these problems? Thanks.

**Comment by DavyMorgan** [comment]
Thanks for your attention on our work. Kuaishou dataset is a private industrial dataset and there is still a series of processes to go before it can be released. Feel free to use the Taobao dataset!

We will upload Taobao dataset to another cloud storage service soon.
