### ISSUE TITLE
Some bugs occur when I'm running this code

### ISSUE THREAD

**Issue by liuhui0401** [tsinghua-fib-lab/SIGIR21-SURGE#4]
(1)AttributeError: module 'tensorflow' has no attribute 'sort'
(2)TypeError: gather_nd() got an unexpected keyword argument 'batch_dims'
(3)TypeError: Expected int32, got None of type '_Message' instead.
Is it normal? I can't solve the last problem. I need your help, thanks.

**Comment by Zzzz-wy** [comment]
Have you solved the third problem？

**Comment by liuhui0401** [comment]
@Zzzz-wy I have tried to use another function to replace the function that reported the error. This method is really useful, the code no longer show the same error.  But I can't solve all the problems. I think it may be caused by a version issue.

**Comment by Zzzz-wy** [comment]
@liuhui0401 I use TensorFlow1.14 to run the model successfully.

**Comment by DavyMorgan** [comment]
We have updated the TensorFlow version in README to 1.15.2, which is supposed to run without these errors.

> (1)AttributeError: module 'tensorflow' has no attribute 'sort' (2)TypeError: gather_nd() got an unexpected keyword argument 'batch_dims' (3)TypeError: Expected int32, got None of type '_Message' instead. Is it normal? I can't solve the last problem. I need your help, thanks.
